title: Cerberus protocol
description: Cerberus is a step-by-step protocol for organisations to securely store bitcoin treasuries without the need for a third-party custodian.

# Important: Reference your custom theme
remote_theme: nwoodfine/style-the-docs@master

# Other settings
baseurl: "/cerberus"
url: "https://nwoodfine.github.io"

# Just the Docs settings
color_scheme: light
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Bitcoin Design":
    - "https://bitcoin.design"

# Add to your existing _config.yml
plugins:
  - jekyll-include-cache
